import type { Metadata } from 'next';
import Link from 'next/link';
import { GuideNav } from '@/components/v2/guide-nav';
import { GuideHero } from '@/components/v2/guide-hero';
import { GuideValuation } from '@/components/v2/guide-valuation';
import { NeighbourhoodTable } from '@/components/v2/neighbourhood-table';
import { Affordability } from '@/components/v2/affordability';
import { ClosingCosts } from '@/components/v2/closing-costs';
import { GuideContact } from '@/components/v2/guide-contact';
import { Reviews } from '@/components/site/reviews';
import { DemoBadge } from '@/components/site/demo-badge';
import { siteConfig } from '@/config/site';

export const metadata: Metadata = {
  title: 'The KW Move Guide',
  description:
    'Straight answers about the Waterloo Region market — home values, neighbourhood comparisons, affordability and closing costs.',
};

export default function MoveGuidePage() {
  return (
    <div className="min-h-screen bg-guide-paper text-guide-ink antialiased">
      <GuideNav />
      <main>
        <GuideHero />
        <GuideValuation />
        <NeighbourhoodTable />
        <Affordability />
        <ClosingCosts />
        {siteConfig.content.showTestimonials && <Reviews variant="guide" />}
        <GuideContact />
      </main>

      <footer className="border-t border-guide-line bg-white">
        <div className="container py-12">
          <div className="flex flex-col gap-8 sm:flex-row sm:items-start sm:justify-between">
            <div>
              <p className="text-[16px] font-semibold text-guide-ink">{siteConfig.teamLong}</p>
              <p className="mt-1 text-[14px] text-guide-muted">{siteConfig.tagline}</p>
            </div>
            <div className="flex flex-wrap gap-x-8 gap-y-2 text-[14px]">
              <a href="#valuation" className="text-guide-inkSoft hover:text-guide-forest">
                Home value
              </a>
              <a href="#compare" className="text-guide-inkSoft hover:text-guide-forest">
                Neighbourhoods
              </a>
              <a href="#afford" className="text-guide-inkSoft hover:text-guide-forest">
                Affordability
              </a>
              <a href="#closing" className="text-guide-inkSoft hover:text-guide-forest">
                Closing costs
              </a>
              <Link href="/admin" className="text-guide-inkSoft hover:text-guide-forest">
                Team login
              </Link>
              <Link href="/" className="text-guide-inkSoft hover:text-guide-forest">
                Alternate design →
              </Link>
            </div>
          </div>

          <p className="mt-10 max-w-3xl text-[12px] leading-relaxed text-guide-muted">
            {siteConfig.brokerage ? `${siteConfig.brokerage}. ` : ''}
            {siteConfig.content.demoMode
              ? 'Demonstration build. Neighbourhood figures and market statistics shown here are sample data for layout purposes and do not represent real transactions. '
              : ''}
            Not intended to solicit buyers or sellers currently under contract. Home valuation
            ranges are generated by an automated model and are not an appraisal. Affordability,
            mortgage and land transfer tax figures are estimates — confirm with your lender and
            lawyer before making an offer.
          </p>
          <p className="mt-4 text-[12px] text-guide-muted">
            © {new Date().getFullYear()} {siteConfig.teamLong}.
          </p>
        </div>
      </footer>

      <DemoBadge />
    </div>
  );
}
